/** The BLE wire protocol: byte-parity with Python transport.frame (vectors
 * generated from the host side), MTU chunking, and reassembler recovery. This
 * is the phone half of the loopback contract the host-side Rig-0 tests pin. */
import { canonicalJson, chunkFrame, framePayload, MAX_FRAME, Reassembler } from "../ble/framing";

// vectors generated by: reality_compiler.v2.transport.frame(obj)
const PARITY: { obj: unknown; bytes: number[] }[] = [
  {
    obj: { t: "command", kind: "wake" },
    bytes: [0, 0, 0, 33, 123, 34, 107, 105, 110, 100, 34, 58, 34, 119, 97, 107, 101, 34, 44, 34, 116, 34, 58, 34, 99, 111, 109, 109, 97, 110, 100, 34, 125],
  },
  {
    obj: { t: "card", payload: { text: "hi" } },
    bytes: [0, 0, 0, 40, 123, 34, 112, 97, 121, 108, 111, 97, 100, 34, 58, 123, 34, 116, 101, 120, 116, 34, 58, 34, 104, 105, 34, 125, 44, 34, 116, 34, 58, 34, 99, 97, 114, 100, 34, 125],
  },
  {
    obj: { t: "figment_swap", id: "fig-1" },
    bytes: [0, 0, 0, 37, 123, 34, 105, 100, 34, 58, 34, 102, 105, 103, 45, 49, 34, 44, 34, 116, 34, 58, 34, 102, 105, 103, 109, 101, 110, 116, 95, 115, 119, 97, 112, 34, 125],
  },
];

describe("framing parity with Python", () => {
  it("canonicalJson sorts keys with compact separators", () => {
    expect(canonicalJson({ t: "x", a: 1 })).toBe('{"a":1,"t":"x"}');
    expect(canonicalJson({ payload: { b: 2, a: 1 }, t: "c" })).toBe('{"payload":{"a":1,"b":2},"t":"c"}');
  });

  it.each(PARITY)("framePayload matches the Python bytes", ({ obj, bytes }) => {
    expect(Array.from(framePayload(obj))).toEqual(bytes);
  });

  it("header total includes itself", () => {
    const f = framePayload({ t: "command", kind: "wake" });
    const total = ((f[0]! << 24) | (f[1]! << 16) | (f[2]! << 8) | f[3]!) >>> 0;
    expect(total).toBe(f.length);
  });

  it("refuses an oversize frame", () => {
    expect(() => framePayload({ t: "card", payload: { x: "y".repeat(MAX_FRAME) } })).toThrow();
  });
});

describe("chunking + reassembly", () => {
  const roundtrip = (obj: unknown, chunkSize: number) => {
    const r = new Reassembler();
    const out: unknown[] = [];
    for (const chunk of chunkFrame(framePayload(obj), chunkSize)) {
      out.push(...r.feed(chunk));
    }
    return out;
  };

  it("reassembles a small frame in one chunk", () => {
    expect(roundtrip({ t: "command", kind: "wake" }, 128)).toEqual([{ t: "command", kind: "wake" }]);
  });

  it("reassembles a large frame split across many chunks", () => {
    const obj = { t: "card", payload: { text: "x".repeat(900) } };
    expect(roundtrip(obj, 128)).toEqual([obj]);
  });

  it.each([1, 3, 7, 64, 127, 128, 200])("survives any chunk size %i", (sz) => {
    const obj = { t: "card", payload: { text: "hello world ".repeat(20) } };
    expect(roundtrip(obj, sz)).toEqual([obj]);
  });

  it("drains two frames concatenated in one chunk", () => {
    const a = framePayload({ t: "command", kind: "a" });
    const b = framePayload({ t: "command", kind: "b" });
    const both = new Uint8Array(a.length + b.length);
    both.set(a);
    both.set(b, a.length);
    const r = new Reassembler();
    const out = r.feed(both);
    expect(out).toEqual([{ t: "command", kind: "a" }, { t: "command", kind: "b" }]);
  });

  it("drops a garbage header and recovers", () => {
    const r = new Reassembler();
    const bogus = Uint8Array.from([255, 255, 255, 255, 123, 125]); // huge length
    expect(r.feed(bogus)).toEqual([]);
    expect(r.dropped).toBe(1);
    const obj = { t: "command", kind: "after" };
    expect(r.feed(framePayload(obj))).toEqual([obj]);
  });

  it("drops a tiny (<5) length header", () => {
    const r = new Reassembler();
    expect(r.feed(Uint8Array.from([0, 0, 0, 2, 9, 9]))).toEqual([]);
    expect(r.dropped).toBe(1);
  });
});
